[package]
name = "4viyolite/serb"
description = "Manual data serialization using Luau buffers"
version = "0.1.1"
license = "MIT"
authors = ["4Viyolite <4viyolite@gmail.com>"]
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/4Viyolite/serb"
realm = "shared"
exclude = [
    ".github/**",
    ".vscode/**",
    "test/**",
    ".gitattributes",
    ".gitignore",
    "*.spec.lua",
    "default.project.jsonc",
    "test.project.jsonc",
    "sourcemap.json"
]
